CREATE TABLE IF NOT EXISTS secretkey (
    id UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4 (),
    secretkeyName VARCHAR(255) NOT NULL,
    user_id UUID NOT NULL,
    secretkeyValue VARCHAR(655) NOT NULL UNIQUE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updateAt TIMESTAMP
)