CREATE TABLE IF NOT EXISTS emails (
    id UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4 (),
    user_id UUID UNIQUE,
    email VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updateAt TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id)
)